### ISSUE TITLE
[$60] allow normal topcoder members to create jobs

### ISSUE THREAD

**Issue by nkumar-topcoder** [topcoder-platform/taas-apis#23] opened 2020-12-02 05:55 UTC
a) Currently, v5/jobs validates for bookingmanager role for job creation. This should be changed to allow for all Topcoder Members "Topcoder User" roles.
b) update POST /v5/jobs to allow all auth user access(include bookingmanager and connectmember as well as normal auth user)
c) update PATCH/PUT/DELETE /v5/jobs/:jobId to allow normal auth user to access the job he/she created. bookingmanager and connectmember can access all jobs as before.
d) update swagger doc

**Comment by veshu** [comment] 2020-12-02 05:55
@nkumar-topcoder, please sign-up with Topcoder X tool<br/><br/>```This is an automated message for veshu via Topcoder X```

**Comment by veshu** [comment] 2020-12-02 05:56
@nkumar-topcoder, please sign-up with Topcoder X tool<br/><br/>```This is an automated message for veshu via Topcoder X```

**Comment by veshu** [comment] 2020-12-02 05:56
@nkumar-topcoder, please sign-up with Topcoder X tool<br/><br/>```This is an automated message for veshu via Topcoder X```

**Comment by veshu** [comment] 2020-12-02 05:57
@nkumar-topcoder, please sign-up with Topcoder X tool<br/><br/>```This is an automated message for veshu via Topcoder X```

**Comment by veshu** [comment] 2020-12-02 06:00
Contest https://www.topcoder.com/challenges/30155268 has been created for this ticket.<br/><br/>```This is an automated message for veshu via Topcoder X```

**Comment by veshu** [comment] 2020-12-02 06:00
Contest https://www.topcoder.com/challenges/30155268 has been updated - it has been assigned to aaron2017.<br/><br/>```This is an automated message for veshu via Topcoder X```

**Comment by imcaizheng** [comment] 2020-12-02 10:14
Fixed with PR https://github.com/topcoder-platform/taas-apis/pull/21

**Comment by imcaizheng** [comment] 2020-12-02 10:36
PR https://github.com/topcoder-platform/taas-apis/pull/25 updates swagger doc.

**Comment by nkumar-topcoder** [comment] 2020-12-02 11:23
@imcaizheng 
1) I am posting as tc member for job candidates. Note that this member is already v5/users. Ideally Jobcandidate POSTING Should not be allowed for tc member. In this case - message should display as “ not allowed or authorised” But message “conflict” is coming.

2) the log shows that, it’s POST v5/users, not sure why is it posting again ?
   a) My guess its trying to recreate a same user handle and getting conflict ? 
   b) When creating JOB also it’s happening. This could be we validate for v5/skills and tc-member doesn’t have u-bann role ? (Note : we are discussing to enable v5/skills search for all members from u-bann side)

Can you please check.

Note : It’s happening for role tc member only, if booking manager role. Then it’s fine.
![image](https://user-images.githubusercontent.com/33625707/100866580-e1b38000-34be-11eb-8052-6ac2227d58bc.png)

**Comment by imcaizheng** [comment] 2020-12-02 15:46
@nkumar-topcoder 
1. currently POST /jobCandidates can be accessed by all TC members as the source code suggests, see https://github.com/topcoder-platform/taas-apis/blob/feature/integration-test-fix/src/services/JobCandidateService.js#L56-L65

    We could apply access rules on the operation if you think it is needed.


2.
    > This could be we validate for v5/skills and tc-member doesn’t have u-bann role ? (Note : we are discussing to enable v5/skills search for all members from u-bann side)

    I don't think so. When we validate for v5/skills, we are using ubahn M2M token rather than the user token from the POST /jobs request, so there is no needs to enable v5/skills search for all members.


3. I believe both conflict errors were caused by the getUserId function. Will look deep into that and get back to you later.

**Comment by nkumar-topcoder** [comment] 2020-12-02 15:53
@imcaizheng 
1. you are right, any tc member can post for a job. Functionality wise this is right. no changes needed.
2. agreed.  
3. ok fine, thank you.

**Comment by imcaizheng** [comment] 2020-12-03 23:09
@nkumar-topcoder 
> My guess its trying to recreate a same user handle and getting conflict ?

Your guess is right.
It is possible the handle stored in your token was already used to create an ubahn user and associated with an userId other than the userId stored in your token.
So when the getUserId function tried to use the userId stored in your token to find an existing ubahn user, it got no record. It then attempted to create new ubahn user with the handle stored in your token, unsurprisingly, ending up conflict error.

Currently the data on Topcoder Dev are not reliable and stable, IMO. To avoid the conflict error, I would
suggest create a new tc member account with different username so you won't be messed up with any existing data.

**Comment by maxceem** [comment] 2020-12-07 09:57
The fix for the issue in this ticket works good.
To track and discuss more the issue with `conflict` error during user ubahn creating I've created a separate issue https://github.com/topcoder-platform/taas-apis/issues/46

**Comment by maxceem** [comment] 2020-12-07 09:58
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30155268<br/><br/>```This is an automated message for maxceem via Topcoder X```

**Closed** 2020-12-07 09:58 UTC
Labels: enhancement, tcx_Assigned, tcx_FixAccepted
