### ISSUE TITLE
[$40] Team shows 6 of 0 team members

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-apis#62] opened 2020-12-16 12:36 UTC
Link to the team https://platform.topcoder-dev.com/taas/myteams/16786

![image](https://user-images.githubusercontent.com/146016/102349506-1ab61f00-3fac-11eb-9ad9-de38708ce2a5.png)

**Comment by maxceem** [comment] 2020-12-17 12:29
I've checked the data. This project has jobs with `numPositions > 0`:

![image](https://user-images.githubusercontent.com/146016/102488046-22d99180-4074-11eb-823b-5423696165e7.png)

1. We have to fix this issue.
2. We have to update the logic - we should only calculate positions of jobs which status is NOT `cancelled` or `closed`.

**Comment by maxceem** [comment] 2020-12-17 12:33
Contest https://www.topcoder.com/challenges/30158839 has been created for this ticket.<br/><br/>```This is an automated message for maxceem via Topcoder X```

**Comment by maxceem** [comment] 2020-12-17 12:33
@imcaizheng ready for pickup.

**Comment by maxceem** [comment] 2020-12-17 21:59
Contest https://www.topcoder.com/challenges/30158839 has been updated - it has been assigned to aaron2017.<br/><br/>```This is an automated message for maxceem via Topcoder X```

**Comment by imcaizheng** [comment] 2020-12-18 00:42
@maxceem I checked in the source code and found that property `totalPositions` is returned only for `GET /taas-teams`. That is why `GET /taas-teams/:projectId` currently returns no `totalPositions`. Are we going to alter the behavior?

**Comment by maxceem** [comment] 2020-12-18 08:57
@imcaizheng no. We only have to fix it in `GET /taas-teams`.

See this screenshot, `totalPosisitions` is not returned by `GET /taas-teams`

![image](https://user-images.githubusercontent.com/146016/102594920-88cf2300-411f-11eb-82fc-ed5e0e2dddf8.png)

Though this team has some valid jobs with `numPositions` as could be seen on this screenshot:

![image](https://user-images.githubusercontent.com/146016/102595048-b2884a00-411f-11eb-8602-0eb05a3a50e8.png)

**Comment by imcaizheng** [comment] 2020-12-19 06:41
I found the cause of the issue is similar to the one for https://github.com/topcoder-platform/taas-apis/issues/51
`GET /taas-teams` internally invoking `JobService.searchJobs({ projectIds })` to search all jobs, which is limited by pagination. We should modify the `searchJobs()` function to allow all jobs returned just like we did before.

**Comment by maxceem** [comment] 2020-12-19 10:06
@imcaizheng great. Agree, let's apply a similar fix.

**Comment by imcaizheng** [comment] 2020-12-19 10:09
PR created https://github.com/topcoder-platform/taas-apis/pull/74

**Comment by maxceem** [comment] 2020-12-19 11:40
Thanks, @imcaizheng. Works great locally and on DEV:

![image](https://user-images.githubusercontent.com/146016/102688508-c4411e80-41ff-11eb-8503-06ab04fd8a18.png)

**Comment by maxceem** [comment] 2020-12-19 11:41
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30158839<br/><br/>```This is an automated message for maxceem via Topcoder X```

**Closed** 2020-12-19 11:41 UTC
Labels: bug, tcx_Assigned, tcx_FixAccepted
