### ISSUE TITLE
[$20] Issue in the email title when the team name has symbols

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-apis#511] opened 2021-08-19 05:49 UTC
**Steps**
Created a team with name 'Don't delete/modify(Notification testing)' from taas intake app
In the email notification, the name is displayed as below

![image](https://user-images.githubusercontent.com/4592712/130014813-13617900-705f-41fd-a422-45a64a5c7f9e.png)

**Comment by maxceem** [comment] 2021-08-20 12:08
### background

This is general issue which caused by escaping login in Projects API see details https://github.com/appirio-tech/connect-app/issues/3485#issuecomment-576497775.

There are 2 encoding happens as per https://github.com/appirio-tech/connect-app/issues/3485#issuecomment-597449604
1. Inside SendGrid and we fixed it by replacing `{{subject}}` with `{{{subject}}}` in sendgrid template.

2. Second encoding happens on the Projects API level it stores encoded data in DB and returns to us already encoded data:
    
    ![image](https://user-images.githubusercontent.com/146016/130230129-148db1b7-ee31-4313-92be-8a178101f755.png)
    
    This leads to the fact that even in UI such team name is displayed with encoded symbols:
    
     ![image](https://user-images.githubusercontent.com/146016/130230465-3df36ae7-688a-491f-9db4-641127cf2912.png)
     

### Task
     
- To fix it once and for all the places what we can do is update code of functions which get data from Projects API like here https://github.com/topcoder-platform/taas-apis/blob/dev/src/common/helper.js#L1021 and here https://github.com/topcoder-platform/taas-apis/blob/dev/src/common/helper.js#L1179 and it should unescape project name before returning using lodash unesacpe method like this https://github.com/appirio-tech/connect-app/blob/hotfix/circleci-smoke-test-on-prod/src/components/TopBar/ProjectToolBar.js#L67
- make sure that there are no other places where we get Project/Team name from Projects API
- provide screenshots verifying subject of notifications doesn't contain endcoded symbols anymore

**Comment by maxceem** [comment] 2021-08-20 12:09
@xxcxy one more task if you like as per https://github.com/topcoder-platform/taas-apis/issues/511#issuecomment-902646176 - only second part is needed as per `Task` description.

**Comment by xxcxy** [comment] 2021-08-20 12:14
Yes. I can take it.

**Comment by maxceem** [comment] 2021-08-20 12:18
Challenge https://www.topcoder.com/challenges/fe13c765-0e88-4cc9-beca-04a53a8d74e7 has been created for this ticket.<br/><br/>```This is an automated message for maxceem via Topcoder X```

**Comment by maxceem** [comment] 2021-08-20 12:18
Challenge https://www.topcoder.com/challenges/fe13c765-0e88-4cc9-beca-04a53a8d74e7 has been assigned to xxcxy.<br/><br/>```This is an automated message for maxceem via Topcoder X```

**Comment by xxcxy** [comment] 2021-08-20 12:37
@maxceem I've created a PR, please review when you have time.
https://github.com/topcoder-platform/taas-apis/pull/519

**Comment by sdgun** [comment] 2021-08-23 04:02
Verified in Dev.

![image](https://user-images.githubusercontent.com/4592712/130388431-1154ab47-569c-46ac-819d-c6423a7edac9.png)

**Comment by maxceem** [comment] 2021-08-23 13:56
Payment task has been updated: https://www.topcoder.com/challenges/fe13c765-0e88-4cc9-beca-04a53a8d74e7
*Payments Complete*
Winner: xxcxy
Copilot: maxceem
Challenge `fe13c765-0e88-4cc9-beca-04a53a8d74e7` has been paid and closed.<br/><br/>```This is an automated message for maxceem via Topcoder X```

**Closed** 2021-08-24 05:10 UTC
Labels: bug, tcx_FixAccepted, tcx_Assigned, tcx_Paid, QA Pass in Dev, P4, Dev env, notifications
