### ISSUE TITLE
[$75] 500 Internal Server error returned for the GET/taas-teams endpoints for some users

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-apis#66] opened 2020-12-17 12:38 UTC
500 Internal server error displayed for the following users/ endpoints
Users: dan_developer, tester1234 (role: topcoder member)
1.`GET /taas-teams`
2. GET /taas-teams/:id 
3. GET /taas-teams/:id/jobs/:jobId
<img width="1440" alt="Screenshot 2020-12-17 at 2 15 53 PM" src="https://user-images.githubusercontent.com/58783823/102488990-dfdae680-4092-11eb-9185-2d5940c14b01.png">

User: topcoderconnect (role: booking manager)
2. GET /taas-teams/:id 
3. GET /taas-teams/:id/jobs/:jobId

<img width="1440" alt="Screenshot 2020-12-17 at 4 07 56 PM" src="https://user-images.githubusercontent.com/58783823/102488981-db163280-4092-11eb-9139-eb443603f62c.png">
<img width="1440" alt="Screenshot 2020-12-17 at 4 08 00 PM" src="https://user-images.githubusercontent.com/58783823/102488988-dea9b980-4092-11eb-9a66-2f6a005a8e6b.png">

Note: for user  tonyj (role:admin) all the three endpoints work correctly)
<img width="1440" alt="Screenshot 2020-12-17 at 6 07 20 PM" src="https://user-images.githubusercontent.com/58783823/102488919-c2a61800-4092-11eb-8830-96cbb687b102.png">
<img width="1440" alt="Screenshot 2020-12-17 at 6 07 24 PM" src="https://user-images.githubusercontent.com/58783823/102488939-c9cd2600-4092-11eb-9a3c-9b69d698efb8.png">
<img width="1440" alt="Screenshot 2020-12-17 at 6 07 31 PM" src="https://user-images.githubusercontent.com/58783823/102488955-cf2a7080-4092-11eb-9f26-2874c04d03a7.png">

**Comment by maxceem** [comment] 2020-12-17 12:54
Contest https://www.topcoder.com/challenges/30158843 has been created for this ticket.<br/><br/>```This is an automated message for maxceem via Topcoder X```

**Comment by maxceem** [comment] 2020-12-17 12:54
@imcaizheng open for pickup.

**Comment by maxceem** [comment] 2020-12-17 21:59
Contest https://www.topcoder.com/challenges/30158843 has been updated - it has been assigned to aaron2017.<br/><br/>```This is an automated message for maxceem via Topcoder X```

**Comment by imcaizheng** [comment] 2020-12-18 03:06
@SathyaJayabal Unable to login to DEV via `dan_developer/tester1234`. Is the username/password correct?

**Comment by SathyaJayabal** [comment] 2020-12-18 03:20
@imcaizheng , those are two different users. Can you message me on the community slack (sathya jayabal)  please and I will send you the passwords .

**Comment by maxceem** [comment] 2020-12-18 10:08
@imcaizheng the error in log:

```
[2020-12-18T09:30:13.317Z] TeamService searchTeams [31mERROR[39m : cannot GET /v5/users/a55fe1bc-1754-45fa-9adc-cf3d6d7c377a?enrich=true (500)
```

So I think the issue is with calling `helper.getUserById` using a regular user token. I think we should fix this kind of issues in a general way by using only M2M tokens for internal calls and stop using the token of users who are calling TaaS API.

For now, let's update this for `TeamService.js` only:
- Use only M2M calls for internal calls of other API endpoints.
- There are only 2 exceptions: `helper.getProjects` and `helper.getProjectById` should use currentUser token instead of M2M token if currentUser is not booking manager and is not machine. This is to check if the regular user has permission to access the team. 
- At the moment it looks like regular user cannot call endpoint `GET /taas-teams/:teamId/job/:jobID` implemented by method `getTeamJob`. In this method we also have to call `helper.getProjectById` to check if user has permission to access the team, if current user is not booking manager and is not machine.
- It would be great if this would clear inside the code. So instead of reassigning `currentUser.jwtToken` with m2m token. Can we use `m2mToken` directly, so we always know if we use currentUser token or `m2mToken` for a particular call.

@imcaizheng does it make sense? do you see any drawbacks in such an approach?

**Comment by imcaizheng** [comment] 2020-12-18 10:32
@maxceem That is, of course, the best solution.

**Comment by imcaizheng** [comment] 2020-12-19 06:01
PR created https://github.com/topcoder-platform/taas-apis/pull/73

**Comment by maxceem** [comment] 2020-12-19 11:12
@imcaizheng works perfectly for me. Just one trivial thing https://github.com/topcoder-platform/taas-apis/pull/73#pullrequestreview-555934077.

@SathyaJayabal this is ready for QA on DEV.

**Comment by SathyaJayabal** [comment] 2020-12-21 04:32
@maxceem , verified on dev. 
<img width="1440" alt="Screenshot 2020-12-21 at 9 49 26 AM" src="https://user-images.githubusercontent.com/58783823/102739597-9381f600-4373-11eb-9301-43678d145da2.png">
<img width="1440" alt="Screenshot 2020-12-21 at 9 52 09 AM" src="https://user-images.githubusercontent.com/58783823/102739601-954bb980-4373-11eb-85f1-8e2e2b790f85.png">
<img width="1440" alt="Screenshot 2020-12-21 at 9 52 14 AM" src="https://user-images.githubusercontent.com/58783823/102739604-97ae1380-4373-11eb-8c20-2e46e9a956c0.png">
<img width="1440" alt="Screenshot 2020-12-21 at 9 52 18 AM" src="https://user-images.githubusercontent.com/58783823/102739607-9977d700-4373-11eb-8d73-a9d37b992820.png">
<img width="1440" alt="Screenshot 2020-12-21 at 10 00 57 AM" src="https://user-images.githubusercontent.com/58783823/102739612-9bda3100-4373-11eb-92b9-33493ec8af3e.png">
<img width="1440" alt="Screenshot 2020-12-21 at 9 48 54 AM" src="https://user-images.githubusercontent.com/58783823/102739588-8e24ab80-4373-11eb-967e-3cba3923a39b.png">

**Comment by maxceem** [comment] 2020-12-21 10:01
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30158843<br/><br/>```This is an automated message for maxceem via Topcoder X```

**Closed** 2020-12-21 10:01 UTC
Labels: QA Pass in Dev, bug, tcx_Assigned, tcx_FixAccepted
