### ISSUE TITLE
Client view Job Candidate Notification

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-apis#475] opened 2021-08-11 11:32 UTC
### Background

We would like to send a email notification to the Job Candidate when client has viewed they profile.

To indicate that client has viewed Job Candidate profile we would use the event when client has downloaded Job Candidate resume in TaaS App.

![image](https://user-images.githubusercontent.com/146016/129019540-f208a1c2-9b1c-4013-a999-9bb56153774d.png)

The resume URL comes from the DB and it just a third party URL. We don't know when someone clicks that URL and downloads the resume. So we would need so kind of a proxy endpoint which would trigger notification and redirect to resume dwonloading.

### Task

- Implement endpoint "GET /jobCandidates/:id/resume" which we could use to trigger notification and which would redirect/trigger resume downloading from URL which we have in DB `JobCandiate.resume`.
- Send email notification if endpoint "GET /jobCandidates/:id/resume" is called by the customer user:
  - we treat the user as customer, if user doesn't have any other roles except of `Topcoder User` https://github.com/topcoder-platform/taas-apis/blob/feature/notifications-api/app-routes.js#L53 and if the user is not the one who is JobCandidate. (regular user who is JobCandidate also has only `Topcoder User` role, so we have to make sure that it's not candidate downloads resume but another user).
  - to send email notification we has send Kafka Message to the topic `notifications.action.create` with the next payload https://gist.github.com/maxceem/bb2ad68d2f8a790f01e3326f9f8015eb.
  - inside data we have to pass: Job Name, Job Candidate user handle.
  - email should be sent to the JobCandidate user
- Update [email template](https://github.com/topcoder-platform/taas-apis/blob/dev/data/notifications-email-template.html) so it can render this type of notification with the text: 
   ```
   Hi {jobCandidateUserHanle}.
   
   Your resume for the job "{Job Name}" has been viewed by the client.
   ```
   
   - type of notification: `taas.notification.job-candidate-resume-viewed`
- We already have a special script to demo Email notifications https://github.com/topcoder-platform/taas-apis/tree/dev/scripts/demo-email-notifications. Run it and it would listen to the Kafka topic `notifications.action.create` and render emails with data from the Kafka message into `out` folder.

- Important: this notification should come only once for the Job Candidate. I guess the only way to make it only one time is add a new column to the JobCandidate model where we would track if this JobCandidate has been already viewed by the customer or no, like `viewedByCustomer` = `true/false`.

- Update Postman/Swagger
- Create migration script
- Update ES mapping in both repositories. Update ES processor.
   
### Branch to work

`feature/notifications-api`

**Comment by yoution** [comment] 2021-08-11 16:55
@maxceem please assign to me

**Comment by yoution** [comment] 2021-08-12 02:34
@maxceem `inside data we have to pass: Job Name, Job Candidate user handle.` 
how can we get the `job name` ? we only have `candidate Id` currently

**Comment by yoution** [comment] 2021-08-12 12:18
@maxceem 
1. ` if the user is not the one who is JobCandidate. `, if I write  `currentUser.userId !== jobCandidate.userId` , is it correct?
the the former is number, the latter is uuid?
2. `Update email template`, is there any web tools I can review the template?

**Comment by maxceem** [comment] 2021-08-12 12:26
@yoution 

1. No. There are 2 kind of user ids UUID and numeric from different API. We have a method which get UUID by numeric id https://github.com/topcoder-platform/taas-apis/blob/feature/notifications-api/src/common/helper.js#L961-L969

2. The template is basically regular HTML with `handlebars` templates. We have 2 ways to view rendered template:
    1. Run script https://github.com/topcoder-platform/taas-apis/tree/dev/scripts/demo-email-notifications. It would listen to Kafka Messages and as soon as it got message to send Email Notification, it would render template inside the `out` folder.
    2. Just put demo data into file https://github.com/topcoder-platform/taas-apis/blob/ca68c6a520740bbccb592d8f80f66c59cb2538a1/data/notifications-email-demo-data.json and run script https://github.com/topcoder-platform/taas-apis/tree/dev/scripts/notification-email-template-renderer which would render the email template with provided data.

**Comment by maxceem** [comment] 2021-08-16 11:43
@yoution the QA is still pending, but payment has been processed https://www.topcoder.com/challenges/823fce23-97ab-4b00-a0bb-491da746b3cb

**Comment by sdgun** [comment] 2021-08-20 05:35
Verified in Dev, issue reported https://github.com/topcoder-platform/taas-apis/issues/506. Will close this once the issue is fixed.

**Comment by sdgun** [comment] 2021-08-30 04:43
Verified in Dev.

**Closed by sdgun** 2021-08-30 04:43 UTC
Labels: QA Fail in Dev, PAID, ACCEPTED
